export const DATA = [
  {
    id: 1,
    documentName: 'GMDSS GOC',
    nationality: 'RUS',
    docNumber: '6533/5563',
    issueDate: 'N/A',
    expiryDate: 'N/A',
    documentType: 'mandatory',
    status: 'pending',
    completed: false,
  },
  {
    id: 2,
    documentName: 'Seagoing service',
    nationality: 'RUS',
    docNumber: '6533/5563',
    issueDate: 'N/A',
    expiryDate: 'N/A',
    documentType: 'mandatory',
    status: 'new',
    completed: false,
  },
  {
    id: 3,
    documentName: 'Security familiarisation',
    nationality: 'RUS',
    docNumber: '6872/234',
    issueDate: '05.08.23',
    expiryDate: '09.08.23',
    documentType: 'optional',
    status: 'new',
    completed: false,
  },
  {
    id: 4,
    documentName: 'Vaccination Certificate',
    nationality: 'RUS',
    docNumber: '6872/2987',
    issueDate: '04.08.23',
    expiryDate: '15.08.23',
    documentType: 'mandatory',
    status: 'new',
    completed: false,
  },
  {
    id: 5,
    documentName: 'Medical fitness certificate',
    nationality: 'RUS',
    docNumber: '6782/1243',
    issueDate: '02.08.23',
    expiryDate: '12.08.23',
    documentType: 'mandatory',
    status: 'new',
    completed: false,
  },
  {
    id: 6,
    documentName: 'Validity of an endorsement ',
    nationality: 'RUS',
    docNumber: '1234/898',
    issueDate: 'N/A',
    expiryDate: 'N/A',
    documentType: 'actionRequired',
    status: 'new',
    completed: true,
  },
  {
    id: 10,
    documentName: 'Ship specific familiarisation',
    nationality: 'RUS',
    docNumber: '6823/76476',
    issueDate: 'N/A',
    expiryDate: 'N/A',
    status: 'new',
    documentType: 'optional',
    completed: true,
  },
  {
    id: 7,
    documentName: 'Survival craft and rescue boats',
    nationality: 'RUS',
    docNumber: '6823/7476',
    issueDate: 'N/A',
    expiryDate: 'N/A',
    documentType: 'optional',
    status: 'new',
    completed: false,
  },
  {
    id: 8,
    documentName: 'Advanced fire fighting',
    nationality: 'RUS',
    docNumber: '6823/7416',
    issueDate: '02.08.23',
    expiryDate: '12.08.23',
    documentType: 'actionRequired',
    status: 'new',
    completed: true,
  },
  {
    id: 9,
    documentName: 'Elementary first aid',
    nationality: 'RUS',
    docNumber: '6823/7456',
    issueDate: '05.08.23',
    expiryDate: '09.08.23',
    documentType: 'mandatory',
    status: 'new',
    completed: false,
  },
  {
    id: 11,
    documentName: 'National certificate of competence',
    nationality: 'RUS',
    docNumber: '6823/74126',
    issueDate: '02.08.23',
    expiryDate: '12.08.23',
    documentType: 'optional',
    status: 'new',
    completed: false,
  },
];

// documentType: 'mandatory' || 'actionRequired' || 'optional',
// status: 'submitted' || 'skipped' || 'new' || 'pending',
// {"completed": false, "id": 1691057621040, "isEditable": false, "isReadOnly": true, "text": "Test 5"}
